/**
 * One-time Walrus Memory (MemWal) setup for HoolClone Tier B testing.
 *
 * Requires in .env:
 *   SUI_PRIVATE_KEY=suiprivkey1...   (owner wallet — setup txs only)
 *
 * Optional:
 *   SUI_NETWORK=mainnet|testnet
 *   MEMWAL_SERVER_URL=https://relayer.memwal.ai
 *   MEMWAL_ACCOUNT_ID=0x...            (skip create if you already have one)
 *   MEMWAL_DELEGATE_PRIVATE_KEY=...    (reuse instead of generating new)
 *   MEMWAL_PACKAGE_ID / MEMWAL_REGISTRY_ID (overrides)
 *
 * Usage:
 *   npm run memwal:setup
 *   npm run memwal:setup -- --write-env
 *   npm run memwal:setup -- --test-write
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SuiJsonRpcClient } from "@mysten/sui/jsonRpc";
import { loadEnv } from "@/lib/load-env";
import {
  fetchRelayerConfig,
  getDefaultRelayerUrl,
  getRegistryId,
  type MemWalNetwork,
} from "@/lib/memwal/contract-config";

loadEnv();

const DELEGATE_LABEL = "HoolClone Server";

function parseArgs(argv: string[]) {
  return {
    writeEnv: argv.includes("--write-env"),
    testWrite: argv.includes("--test-write"),
  };
}

function requireOwnerPrivateKey(): string {
  const key =
    process.env.SUI_PRIVATE_KEY?.trim() ||
    process.env.MEMWAL_OWNER_PRIVATE_KEY?.trim();
  if (!key) {
    console.error(
      "Missing SUI_PRIVATE_KEY in .env (bech32 suiprivkey1... from your Sui wallet).",
    );
    console.error("This key is only used for on-chain setup txs. Remove it after setup.");
    process.exit(1);
  }
  return key;
}

function resolveNetwork(): MemWalNetwork {
  const network = (process.env.SUI_NETWORK ?? "mainnet").trim();
  if (network === "mainnet" || network === "testnet") return network;
  console.error(`Unsupported SUI_NETWORK=${network}. Use mainnet or testnet.`);
  process.exit(1);
}

function resolveServerUrl(network: MemWalNetwork): string {
  return (
    process.env.MEMWAL_SERVER_URL?.trim() || getDefaultRelayerUrl(network)
  );
}

async function createSuiClient(suiRpcUrl: string, network: MemWalNetwork) {
  return new SuiJsonRpcClient({ url: suiRpcUrl, network });
}

async function getOwnerAddress(
  suiPrivateKey: string,
  suiClient: SuiJsonRpcClient,
): Promise<string> {
  const { decodeSuiPrivateKey } = await import("@mysten/sui/cryptography");
  const { Ed25519Keypair } = await import("@mysten/sui/keypairs/ed25519");
  const { secretKey } = decodeSuiPrivateKey(suiPrivateKey);
  const keypair = Ed25519Keypair.fromSecretKey(secretKey);
  const address = keypair.getPublicKey().toSuiAddress();

  const balance = await suiClient.getBalance({ owner: address });
  const mist = BigInt(balance.totalBalance);
  if (mist < BigInt(10_000_000)) {
    console.warn(
      `Warning: wallet ${address} has low SUI (${balance.totalBalance} MIST). Setup txs may fail.`,
    );
  }

  return address;
}

async function findExistingAccount(
  suiClient: SuiJsonRpcClient,
  owner: string,
  packageId: string,
): Promise<string | null> {
  const result = await suiClient.getOwnedObjects({
    owner,
    filter: { StructType: `${packageId}::account::MemWalAccount` },
    options: { showType: true },
  });
  return result.data[0]?.data?.objectId ?? null;
}

function isDuplicateDelegateError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /duplicate|already|exists|0\)/i.test(message);
}

function formatEnvBlock(values: Record<string, string>): string {
  return [
    "",
    "# --- Walrus Memory (generated by npm run memwal:setup) ---",
    `MEMORY_BACKEND=walrus`,
    `MEMWAL_ACCOUNT_ID=${values.MEMWAL_ACCOUNT_ID}`,
    `MEMWAL_DELEGATE_PRIVATE_KEY=${values.MEMWAL_DELEGATE_PRIVATE_KEY}`,
    `MEMWAL_SERVER_URL=${values.MEMWAL_SERVER_URL}`,
    `SUI_NETWORK=${values.SUI_NETWORK}`,
    "# Remove SUI_PRIVATE_KEY after setup if you no longer need on-chain admin txs",
    "",
  ].join("\n");
}

function upsertEnvFile(filePath: string, updates: Record<string, string>) {
  const keys = new Set(Object.keys(updates));
  let lines: string[] = [];

  try {
    lines = readFileSync(filePath, "utf8").split(/\r?\n/);
  } catch {
    lines = [];
  }

  const seen = new Set<string>();
  const out: string[] = [];

  for (const line of lines) {
    const match = line.match(/^([A-Z0-9_]+)=/);
    if (match && keys.has(match[1])) {
      if (!seen.has(match[1])) {
        out.push(`${match[1]}=${updates[match[1]]}`);
        seen.add(match[1]);
      }
      continue;
    }
    out.push(line);
  }

  for (const [key, value] of Object.entries(updates)) {
    if (!seen.has(key)) {
      out.push(`${key}=${value}`);
    }
  }

  writeFileSync(filePath, `${out.join("\n").replace(/\n+$/, "")}\n`, "utf8");
}

async function main() {
  const { MemWal } = await import("@mysten-incubation/memwal");
  const { addDelegateKey, createAccount, generateDelegateKey } = await import(
    "@mysten-incubation/memwal/account"
  );

  const { writeEnv, testWrite } = parseArgs(process.argv.slice(2));
  const suiPrivateKey = requireOwnerPrivateKey();
  const preferredNetwork = resolveNetwork();
  const serverUrl = resolveServerUrl(preferredNetwork);

  console.log("HoolClone MemWal setup");
  console.log("====================");
  console.log(`Relayer: ${serverUrl}`);

  const relayer = await fetchRelayerConfig(serverUrl);
  if (relayer.network !== preferredNetwork) {
    console.warn(
      `Warning: SUI_NETWORK=${preferredNetwork} but relayer reports ${relayer.network}.`,
    );
  }

  const packageId =
    process.env.MEMWAL_PACKAGE_ID?.trim() || relayer.packageId;
  const registryId = getRegistryId(
    relayer.network,
    process.env.MEMWAL_REGISTRY_ID?.trim(),
  );

  console.log(`Package:  ${packageId}`);
  console.log(`Registry: ${registryId}`);

  const suiClient = await createSuiClient(relayer.suiRpcUrl, relayer.network);
  const owner = await getOwnerAddress(suiPrivateKey, suiClient);
  console.log(`Owner:    ${owner}`);

  const txBase = {
    packageId,
    suiPrivateKey,
    suiNetwork: relayer.network,
    suiClient,
  } as const;

  let accountId = process.env.MEMWAL_ACCOUNT_ID?.trim() ?? "";

  if (accountId) {
    console.log(`Using MEMWAL_ACCOUNT_ID from env: ${accountId}`);
  } else {
    const existing = await findExistingAccount(suiClient, owner, packageId);
    if (existing) {
      accountId = existing;
      console.log(`Found existing MemWal account: ${accountId}`);
    } else {
      console.log("Creating MemWal account on-chain (requires SUI for gas)...");
      const created = await createAccount({ ...txBase, registryId });
      accountId = created.accountId;
      if (!accountId) {
        throw new Error(
          "createAccount succeeded but accountId was not found in transaction effects.",
        );
      }
      console.log(`Created account: ${accountId} (tx ${created.digest})`);
    }
  }

  let delegatePrivateKey = process.env.MEMWAL_DELEGATE_PRIVATE_KEY?.trim();
  let delegatePublicKey: Uint8Array;

  async function publicKeyFromPrivateHex(hex: string): Promise<Uint8Array> {
    const ed = await import("@noble/ed25519");
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < bytes.length; i++) {
      bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    }
    return ed.getPublicKeyAsync(bytes);
  }

  if (delegatePrivateKey) {
    console.log("Using existing MEMWAL_DELEGATE_PRIVATE_KEY from env.");
    delegatePublicKey = await publicKeyFromPrivateHex(delegatePrivateKey);
  } else {
    console.log("Generating new delegate key for the server...");
    const delegate = await generateDelegateKey();
    delegatePrivateKey = delegate.privateKey;
    delegatePublicKey = delegate.publicKey;
    console.log(`Delegate Sui address: ${delegate.suiAddress}`);
  }

  console.log("Registering delegate key on-chain...");
  try {
    const added = await addDelegateKey({
      ...txBase,
      accountId,
      publicKey: delegatePublicKey,
      label: DELEGATE_LABEL,
    });
    console.log(`Delegate registered (tx ${added.digest})`);
  } catch (error) {
    if (isDuplicateDelegateError(error)) {
      console.log("Delegate key already registered on this account — continuing.");
    } else {
      throw error;
    }
  }

  console.log("Checking relayer health...");
  const memwal = MemWal.create({
    key: delegatePrivateKey,
    accountId,
    serverUrl,
  });
  const health = await memwal.health();
  console.log(`Relayer status: ${health.status} (${health.version ?? health.relayerVersion ?? "unknown"})`);

  if (testWrite) {
    console.log("Test write to namespace HoolClone:setup-test ...");
    const result = await memwal.rememberAndWait(
      "[remembered] HoolClone MemWal setup smoke test",
      "HoolClone:setup-test",
      { timeoutMs: 90_000 },
    );
    console.log(`Test memory stored. blob_id=${result.blob_id}`);
  }

  memwal.destroy();

  const envValues = {
    MEMWAL_ACCOUNT_ID: accountId,
    MEMWAL_DELEGATE_PRIVATE_KEY: delegatePrivateKey,
    MEMWAL_SERVER_URL: serverUrl,
    SUI_NETWORK: relayer.network,
  };

  console.log("\nAdd these to your .env:\n");
  console.log(formatEnvBlock(envValues));

  if (writeEnv) {
    const envPath = resolve(process.cwd(), ".env");
    upsertEnvFile(envPath, {
      MEMORY_BACKEND: "walrus",
      ...envValues,
    });
    console.log(`Updated ${envPath}`);
  } else {
    console.log("Tip: run with --write-env to patch .env automatically.");
  }

  console.log("\nNext steps:");
  console.log("  1. Restart: npm run dev");
  console.log("  2. curl http://localhost:3000/api/admin/memwal-health");
  console.log("  3. Train at /train, then check /memory");
  console.log("\nSecurity: remove SUI_PRIVATE_KEY from .env when done (keep delegate key).");
}

main().catch((error) => {
  console.error("\nSetup failed:", error instanceof Error ? error.message : error);
  process.exit(1);
});
